### PR TITLE
fix cli args usage

### LINKED ISSUE #68: Error when using pipe
When running pino-mongodb like echo '{"name": "Viktor"}' | pino-mongodb [options] [mongo-url] I receive error "collection name must be a String". 

in pino-mongodb.js

` 
    const collection = db.collection(program.collection)
  `

should be:
`
    const collection = db.collection(program.opts().collection)
  `

### PR DESCRIPTION
**Pull request by Eomm**
fix #68

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by Eomm** [comment]
The CI fails on node12 because `childprocess.kill('SIGINT')` does not trigger the event on the spawned process.

Not found the solution at the moment

**Comment by mcollina** [comment]
Can we just skip that text on Node v12?

**Comment by Eomm** [comment]
Increasing the timeout solved

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
